name: Preview Comment

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR info
        uses: actions-ecosystem/action-get-merged-pull-request@v1
        id: pr

      - name: Create Preview Comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          REPO="${GITHUB_REPOSITORY}"
          BRANCH="${{ github.event.pull_request.head.ref }}"

          PREVIEW_URL="https://htmlpreview.github.io/?https://raw.githubusercontent.com/${REPO}/refs/heads/${BRANCH}/index.html"

          echo "PREVIEW_URL=${PREVIEW_URL}" >> $GITHUB_ENV

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            🚀 Preview ready:
            ${{ env.PREVIEW_URL }}
